# version: "3.3"
name: ${DOCKER_PROJECT_NAME}
services:
  postgres:
    build: ./postgres_database
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-PgiC9sPostgres@123}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    ports:
      - "${DATABASE_PORT}:5432"
    # networks:
    #   - postgres
    restart: unless-stopped

  rabbitmq: 
    image: rabbitmq:3.9-management
    environment: 
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-username}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-password}
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    restart: unless-stopped

  backend:
    build:
      context: ./
      dockerfile: ./fastapi/Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-PgiC9sPostgres@123}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_IP: ${DATABASE_IP}
      DATABASE_NAME: ${DATABASE_NAME}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-username}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-password}
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ${LOCAL_STORAGE_DIR}:${STORAGE_DIR}
    ports:
      - "${FASTAPI_PORT}:5111"

  # AI_service: 


volumes:
  postgres_data:
    name: ${DOCKER_POSTGRES_VOLUME_NAME}
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ${LOCAL_DATABASE_DIR}

  # init_db:
  #   build:
  #     context: ../
  #     dockerfile: ./backend/init_db/Dockerfile
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER:-postgres}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-PgiC9sPostgres@123}
  #     DATABASE_USER: ${DATABASE_USER}
  #     DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  #     DATABASE_PORT: ${DATABASE_PORT}
  #     DATABASE_IP: ${DATABASE_IP}
  #     DATABASE_NAME: ${DATABASE_NAME}
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   volumes:
  #     - ${STORAGE_DIR}:${STORAGE_DIR}

  # backend:
  #   build:
  #     context: ../
  #     dockerfile: ./backend/fastapi/Dockerfile
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER:-postgres}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-PgiC9sPostgres@123}
  #     DATABASE_USER: ${DATABASE_USER}
  #     DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  #     DATABASE_PORT: ${DATABASE_PORT}
  #     DATABASE_IP: ${DATABASE_IP}
  #     DATABASE_NAME: ${DATABASE_NAME}
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   volumes:
  #     - ${STORAGE_DIR}:${STORAGE_DIR}

  #   ports:
  #     - "${FASTAPI_PORT}:5001"

  # api_call:
  #   build:
  #     context: ../
  #     dockerfile: ./backend/api_call/Dockerfile
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER:-postgres}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-PgiC9sPostgres@123}
  #     DATABASE_USER: ${DATABASE_USER}
  #     DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  #     DATABASE_PORT: ${DATABASE_PORT}
  #     DATABASE_IP: ${DATABASE_IP}
  #     DATABASE_NAME: ${DATABASE_NAME}
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   volumes:
  #     - ${STORAGE_DIR}:${STORAGE_DIR}
  #     - ${ROOT_MODEL_DIR}:${ROOT_MODEL_DIR}

  #   ports:
  #     - "${API_CALL_JOB_MANAGER_PORT}:5000"

# networks:
#   postgres:
#     driver: bridge

# volumes:
#   postgres_data:
#     name: ${DOCKER_POSTGRES_VOLUME_NAME}
#     driver: local
#     driver_opts:
#       type: "none"
#       o: "bind"
#       device: ${DATABASE_DIR}
